const UserCRM = require('../models/UserCRM');

const buildDefaultCrmName = () => {
  const timestamp = new Date().toISOString().replace('T', ' ').slice(0, 16);
  return `Lead Export ${timestamp}`;
};

const normalizeLead = (lead) => {
  const firstName = lead.First_Name || lead.firstName || '';
  const lastName = lead.Last_Name || lead.lastName || '';

  return {
    leadId: lead.id?.toString?.() || lead.leadId?.toString?.() || '',
    firstName,
    lastName,
    fullName: `${firstName} ${lastName}`.trim() || lead.fullName || '',
    title: lead.title || lead.jobTitle || '',
    company: lead.Account_Name || lead.company || '',
    email: lead.email || '',
    phone: lead.phone || '',
    mobile: lead.mobile || '',
    industry: lead.GTM_Industry || lead.industry || '',
    sector: lead.GTM_Sector || lead.sector || '',
    segment: lead.Account_Sub_Segment || lead.segment || '',
    country: lead.Mailing_Country || lead.country || '',
    employees: lead.employees ?? null,
    rawData: lead
  };
};

// @desc    Get user CRM objects
// @route   GET /api/user-crm
// @access  Private
const getUserCrmObjects = async (req, res) => {
  try {
    const userId = req.user.id || req.user._id;

    const crmObjects = await UserCRM.find({ userId })
      .sort({ createdAt: -1 })
      .lean();

    const data = crmObjects.map((crmObject) => {
      const emailLeadCount = (crmObject.leads || []).filter(
        (lead) => typeof lead.email === 'string' && lead.email.includes('@')
      ).length;

      return {
        id: crmObject._id,
        crmObjectName: crmObject.crmObjectName,
        totalLeads: crmObject.totalLeads,
        emailLeadCount,
        exportFormat: crmObject.exportFormat,
        source: crmObject.source,
        searchCriteria: crmObject.searchCriteria || {},
        metadata: crmObject.metadata || {},
        createdAt: crmObject.createdAt,
        updatedAt: crmObject.updatedAt,
        leads: crmObject.leads || []
      };
    });

    res.json({
      success: true,
      data
    });
  } catch (error) {
    console.error('Error fetching CRM objects:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to fetch CRM objects',
      error: error.message
    });
  }
};

// @desc    Save exported leads to user CRM collection
// @route   POST /api/user-crm
// @access  Private
const createUserCrmObject = async (req, res) => {
  try {
    const userId = req.user.id || req.user._id;
    const {
      crmObjectName,
      leads,
      exportFormat,
      searchCriteria = {},
      metadata = {},
      source = 'export'
    } = req.body;

    if (!Array.isArray(leads) || leads.length === 0) {
      return res.status(400).json({
        success: false,
        message: 'At least one lead is required to save a CRM object'
      });
    }

    const trimmedName = typeof crmObjectName === 'string' ? crmObjectName.trim() : '';
    const finalName = trimmedName || buildDefaultCrmName();
    const normalizedLeads = leads.map(normalizeLead);

    const crmObject = await UserCRM.create({
      userId,
      crmObjectName: finalName,
      source,
      exportFormat,
      totalLeads: normalizedLeads.length,
      searchCriteria: {
        industry: searchCriteria.industry || '',
        company: searchCriteria.company || '',
        companySegment: searchCriteria.companySegment || '',
        location: searchCriteria.location || ''
      },
      leadIds: normalizedLeads.map((lead) => lead.leadId).filter(Boolean),
      leads: normalizedLeads,
      metadata: {
        requestedCount: metadata.requestedCount ?? normalizedLeads.length,
        matchedCount: metadata.matchedCount ?? normalizedLeads.length,
        creditsConsumed: metadata.creditsConsumed ?? 0,
        remainingCreditsAfter: metadata.remainingCreditsAfter,
        exportedAt: metadata.exportedAt ? new Date(metadata.exportedAt) : new Date(),
        autoGeneratedName: !trimmedName,
        exportedBy: metadata.exportedBy || 'hotlead-inbox'
      }
    });

    res.status(201).json({
      success: true,
      message: 'CRM object saved successfully',
      data: {
        id: crmObject._id,
        crmObjectName: crmObject.crmObjectName,
        totalLeads: crmObject.totalLeads,
        exportFormat: crmObject.exportFormat,
        source: crmObject.source,
        createdAt: crmObject.createdAt
      }
    });
  } catch (error) {
    console.error('Error saving CRM object:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to save CRM object',
      error: error.message
    });
  }
};

module.exports = {
  getUserCrmObjects,
  createUserCrmObject
};
