// ─────────────────────────────────────────────────────────────────────────────
// Seed: ProjectCatalog + ProjectPricing
// Run:  npm run seed:projects
// ─────────────────────────────────────────────────────────────────────────────

const mongoose = require('mongoose');
const { config } = require('../config/config');
const ProjectCatalog = require('../models/ProjectCatalog');
const ProjectPricing  = require('../models/ProjectPricing');

// ── 1. RAW PROJECT DATA ───────────────────────────────────────────────────────
// (icons stripped — UI-only fields not stored in DB)

const PROJECTS_DATA = [
  {
    slug: 'outbound-list-builder',
    category: 'outbound',
    number: 'Project 1.1 – 1.2',
    title: 'Dream List Builder',
    subtitle: 'Build your outbound list from 5M+ verified contacts',
    tagline: 'Get B2B contact info for every decision maker with full profiles in seconds',
    description: 'Identify and build a hyper-targeted outbound contact list drawn from 5M+ verified B2B records. Our experts define your Ideal Customer Profile (ICP), search across data sources, enrich every contact with decision-maker profiles, verified emails, phone numbers, and LinkedIn URLs — then deliver a clean, CRM-ready sheet.',
    badge: 'Most Popular',
    difficulty: 'Beginner',
    duration: '3–7 days',
    subProjects: ['Contact Discovery (1.1)', 'Profile Enrichment & Verification (1.2)'],
    howItWorks: [
      'Define your Ideal Customer Profile (ICP) together with the expert',
      'AI scans 5M+ contact database + 3rd-party enrichment sources',
      'Expert verifies emails, phones, and LinkedIn profiles',
      'Deliver structured, CRM-ready outbound list with full decision-maker profiles',
    ],
    deliverables: [
      'Verified contact list (CSV / CRM format)',
      'Decision-maker profiles with titles & LinkedIn',
      'Company intelligence (size, revenue, tech stack)',
      'ICP score for each contact',
    ],
    subjects: ['ICP Strategy', 'Data Research', 'Contact Enrichment', 'Email Verification', 'LinkedIn Intelligence', 'CRM Integration'],
    tools: ['Apollo.io', 'ZoomInfo', 'Clay', 'Hunter.io', 'LinkedIn Sales Navigator', 'HubSpot'],
    expertSkills: ['Lead Generation', 'Data Research', 'Apollo.io', 'ZoomInfo', 'Clay', 'B2B Marketing'],
    targetFor: ['B2B SaaS', 'Coaches', 'Consultants', 'Professional Services', 'Marketing Agencies'],
    matchIndustries: ['B2B SaaS', 'Technology & Software', 'Marketing', 'Consulting', 'Professional Services'],
    faq: [
      { q: 'How accurate is the contact data?', a: 'We guarantee 90%+ email deliverability. Every contact is triple-verified through real-time email validation, phone lookup, and LinkedIn cross-reference.' },
      { q: 'How long does it take?', a: 'Most lists (up to 500 contacts) are delivered in 3–5 business days. Larger lists (1,000+) take 5–7 days depending on ICP complexity.' },
      { q: 'Can I target specific companies?', a: 'Yes — provide a target account list and the expert will find the right decision-maker contacts within those exact companies.' },
    ],
    successHighlight: 'Cut prospecting time by 80% — from 3 weeks to 3 days for a consulting firm',
    successROI: '80% time saved',
    successStory: { company: 'Growth Consulting Co.', result: '500 verified contacts delivered in 4 days', industry: 'Consulting' },
    stats: {
      expertCount: 14, completedCount: 62, avgRating: 4.8, trendingCount: 47,
      trendingLabel: '47 businesses started this week',
      nearbyExpertCount: { Mumbai: 4, Bangalore: 6, Delhi: 3, Hyderabad: 2, Pune: 3, Chennai: 2 },
      matchScore: { 'B2B SaaS': 96, 'Technology & Software': 91, 'Marketing': 88, 'Consulting': 94, 'Professional Services': 90, 'Ecommerce': 72, 'Healthcare': 65, 'Education': 68 },
    },
    expertCities: ['Mumbai', 'Bangalore', 'Delhi', 'Hyderabad', 'Pune', 'Chennai'],
    theme: { gradient: 'from-blue-500 to-blue-700', bgLight: 'bg-blue-50', textColor: 'text-blue-700', borderColor: 'border-blue-200' },
    budgetRange: '₹15,000 – ₹75,000',
    isFeatured: true, isTrending: true,
  },
  {
    slug: 'sales-outreach-automation',
    category: 'outreach',
    number: 'Project 2.1 – 2.2',
    title: 'Sales Outreach Automation',
    subtitle: 'Automate your GTM processes across email, LinkedIn & phone',
    tagline: 'Automate your sales and go-to-market processes through email, LinkedIn, and phone calls',
    description: 'End-to-end outreach automation: expert sets up multi-channel sequences across cold email, LinkedIn DMs, and cold calling scripts. Includes copywriting, A/B testing, reply handling workflows, and CRM sync — so your pipeline fills on autopilot.',
    badge: 'High ROI',
    difficulty: 'Intermediate',
    duration: '1–2 weeks',
    subProjects: ['Email Sequence Setup (2.1)', 'LinkedIn + Phone Automation (2.2)'],
    howItWorks: [
      'Audit your current outreach stack and CRM',
      'Build multi-channel sequence: email → LinkedIn → phone',
      'Write personalized copy for each touchpoint with A/B variants',
      'Set up automation in your tool (Outreach / Apollo / Lemlist)',
      'Launch, monitor, and optimise reply rates weekly',
    ],
    deliverables: [
      'Multi-step email sequences (3-7 touchpoints)',
      'LinkedIn connection + DM templates',
      'Cold call scripts and objection handling',
      'CRM workflow & tagging setup',
      'Weekly performance report',
    ],
    subjects: ['Cold Email Strategy', 'LinkedIn Outreach', 'Sequence Building', 'Copywriting', 'CRM Integration', 'A/B Testing'],
    tools: ['Outreach.io', 'Apollo.io', 'Lemlist', 'Instantly.ai', 'HubSpot', 'Salesforce'],
    expertSkills: ['Cold Email', 'LinkedIn Outreach', 'Outreach.io', 'Apollo', 'Lemlist', 'CRM', 'Copywriting'],
    targetFor: ['B2B SaaS', 'Consultants', 'Marketing Agencies', 'Professional Services'],
    matchIndustries: ['B2B SaaS', 'Technology & Software', 'Marketing', 'Sales', 'Consulting'],
    faq: [
      { q: 'What reply rates can I expect?', a: 'Across our campaigns, average cold email reply rates are 8–15% and LinkedIn connection acceptance is 25–40%.' },
      { q: 'Do I need to have a tool already?', a: 'No. The expert will recommend the right tool for your budget and set it up from scratch.' },
      { q: 'Is this GDPR/CAN-SPAM compliant?', a: 'Yes. Every sequence is built with compliant opt-out mechanisms.' },
    ],
    successHighlight: '$180K pipeline built in 6 weeks for a B2B SaaS startup with 3-touch sequences',
    successROI: '$180K pipeline',
    successStory: { company: 'B2B SaaS Startup', result: '$180K pipeline in 6 weeks', industry: 'B2B SaaS' },
    stats: {
      expertCount: 18, completedCount: 89, avgRating: 4.9, trendingCount: 38,
      trendingLabel: '38 active campaigns launched this week',
      nearbyExpertCount: { Mumbai: 5, Bangalore: 8, Delhi: 4, Hyderabad: 3, Pune: 4, Chennai: 2 },
      matchScore: { 'B2B SaaS': 98, 'Technology & Software': 93, 'Marketing': 95, 'Consulting': 91, 'Professional Services': 89, 'Ecommerce': 70, 'Healthcare': 62, 'Education': 65 },
    },
    expertCities: ['Bangalore', 'Mumbai', 'Delhi', 'Hyderabad', 'Pune', 'Noida'],
    theme: { gradient: 'from-orange-500 to-orange-600', bgLight: 'bg-orange-50', textColor: 'text-orange-700', borderColor: 'border-orange-200' },
    budgetRange: '₹20,000 – ₹90,000',
    isFeatured: false, isTrending: true,
  },
  {
    slug: 'ai-email-sales-agency',
    category: 'email',
    number: 'Email Service Agency',
    title: 'AI Email Sales Agency',
    subtitle: 'Hire AI Sales Agents to generate meetings & sales',
    tagline: 'Start with Email Outbound, Move towards Voice agents for verified meeting booking',
    description: 'A fully managed email sales agency powered by AI. Experts build, run, and optimise cold email infrastructure that books qualified meetings for your business — handling deliverability, personalisation at scale, reply management, and handoff to your sales team.',
    badge: 'Managed Service',
    difficulty: 'Advanced',
    duration: 'Ongoing (monthly retainer)',
    subProjects: ['Cold Email Infrastructure', 'AI Reply Handling', 'Voice Agent Handoff'],
    howItWorks: [
      'Set up dedicated sending domains and warm them up',
      'Build AI-personalised email campaigns at scale',
      'AI handles initial replies and qualifies leads automatically',
      'Warm leads handed off to voice agents or sales rep',
      'Track meetings booked and revenue attributed',
    ],
    deliverables: [
      'Warmed sending infrastructure (3–5 domains)',
      'Personalised email campaign at scale',
      'AI reply classification & follow-up',
      'Monthly meetings booked report',
      'Pipeline value tracking',
    ],
    subjects: ['Email Infrastructure', 'Domain Warmup', 'AI Personalization', 'Deliverability', 'Reply Handling', 'Voice Agent Handoff'],
    tools: ['Instantly.ai', 'Smartlead', 'Mailforge', 'Clay', 'GPT-4', 'Vapi.ai'],
    expertSkills: ['Cold Email', 'Email Deliverability', 'AI Automation', 'Instantly.ai', 'Smartlead', 'Copywriting'],
    targetFor: ['Ecommerce', 'Marketing Agencies', 'B2B SaaS', 'Professional Services'],
    matchIndustries: ['Ecommerce', 'Marketing', 'B2B SaaS', 'Technology & Software', 'Professional Services'],
    faq: [
      { q: 'How many meetings can I expect?', a: 'Our managed clients average 15–50 qualified meetings per month depending on audience size and budget.' },
      { q: 'What is the minimum commitment?', a: 'We recommend at least a 3-month engagement to properly warm domains and optimise campaigns.' },
      { q: 'How does the voice agent handoff work?', a: 'Once a reply shows buying intent, a trained voice AI agent follows up by phone within minutes.' },
    ],
    successHighlight: '47 qualified meetings booked in month 1 for a marketing agency — zero manual work',
    successROI: '47 meetings / month 1',
    successStory: { company: 'Marketing Agency', result: '47 meetings in month 1', industry: 'Marketing' },
    stats: {
      expertCount: 9, completedCount: 31, avgRating: 4.7, trendingCount: 12,
      trendingLabel: '12 agencies onboarded this month',
      nearbyExpertCount: { Mumbai: 3, Bangalore: 4, Delhi: 2, Hyderabad: 2 },
      matchScore: { 'Ecommerce': 95, 'Marketing': 92, 'B2B SaaS': 88, 'Technology & Software': 82, 'Professional Services': 79, 'Consulting': 75, 'Healthcare': 58, 'Education': 55 },
    },
    expertCities: ['Bangalore', 'Mumbai', 'Delhi', 'Hyderabad'],
    theme: { gradient: 'from-green-500 to-emerald-600', bgLight: 'bg-green-50', textColor: 'text-green-700', borderColor: 'border-green-200' },
    budgetRange: '₹40,000 – ₹1,50,000/mo',
    isFeatured: false, isTrending: false,
  },
  {
    slug: 'brand-voice-social',
    category: 'brand',
    number: 'Brand Voice Project',
    title: 'Brand Voice & Thought Leadership',
    subtitle: "Activate your brand's voice on LinkedIn, X & industry communities",
    tagline: 'Activate Thought leadership of your company on Social Media — LinkedIn, X & Industry Communities',
    description: 'Build an authoritative brand presence through consistent, high-quality thought leadership content. Experts develop your unique brand voice, create a content calendar, ghostwrite posts for LinkedIn and X, and engage with your target communities.',
    badge: 'Top Rated',
    difficulty: 'Intermediate',
    duration: 'Ongoing (monthly)',
    subProjects: ['Brand Voice Development', 'Content Calendar & Ghostwriting', 'Community Engagement'],
    howItWorks: [
      'Brand voice discovery workshop (tone, values, audience)',
      'Competitive content audit and positioning strategy',
      'Build 30/60/90-day content calendar',
      'Expert ghostwrites and schedules posts consistently',
      'Track engagement, followers, and inbound leads generated',
    ],
    deliverables: [
      'Brand voice guide document',
      '30-day content calendar',
      '8–12 LinkedIn/X posts per month',
      'Community comment & engagement strategy',
      'Monthly analytics report',
    ],
    subjects: ['Brand Voice Development', 'Content Strategy', 'LinkedIn Marketing', 'Twitter/X Growth', 'Community Engagement', 'Thought Leadership'],
    tools: ['LinkedIn', 'Twitter/X', 'Taplio', 'Buffer', 'Canva', 'Notion'],
    expertSkills: ['Content Strategy', 'Ghostwriting', 'LinkedIn Marketing', 'Twitter/X', 'Brand Strategy', 'Copywriting'],
    targetFor: ['Coaches', 'Consultants', 'Course Creators', 'Professional Services', 'Ecommerce'],
    matchIndustries: ['Coaching', 'Consulting', 'Education', 'Ecommerce', 'Professional Services', 'Marketing'],
    faq: [
      { q: 'Do you write the posts or do I?', a: 'Your expert ghostwrites everything based on your voice guide — you review and approve before anything goes live.' },
      { q: 'How long before I see results?', a: 'Engagement growth typically starts in weeks 3–4. Inbound leads from content usually appear in months 2–3.' },
      { q: 'Can you manage multiple platforms?', a: 'Yes. We can simultaneously manage LinkedIn, X (Twitter), and industry-specific communities under one retainer.' },
    ],
    successHighlight: '3.2x inbound lead increase in 60 days for a SaaS founder',
    successROI: '3.2x inbound leads',
    successStory: { company: 'SaaS Founder', result: '0 to 12 inbound leads/month in 60 days', industry: 'B2B SaaS' },
    stats: {
      expertCount: 22, completedCount: 104, avgRating: 4.9, trendingCount: 52,
      trendingLabel: '52 coaches & consultants joined this week',
      nearbyExpertCount: { Mumbai: 7, Bangalore: 9, Delhi: 5, Hyderabad: 4, Pune: 5, Chennai: 3, Kolkata: 2 },
      matchScore: { 'Coaching': 98, 'Consulting': 97, 'Education': 94, 'Ecommerce': 90, 'Professional Services': 92, 'Marketing': 95, 'B2B SaaS': 85, 'Technology & Software': 80 },
    },
    expertCities: ['Mumbai', 'Bangalore', 'Delhi', 'Pune', 'Hyderabad', 'Chennai', 'Kolkata'],
    theme: { gradient: 'from-violet-500 to-purple-600', bgLight: 'bg-violet-50', textColor: 'text-violet-700', borderColor: 'border-violet-200' },
    budgetRange: '₹15,000 – ₹60,000/mo',
    isFeatured: true, isTrending: true,
  },
  {
    slug: 'traffic-abm',
    category: 'traffic',
    number: 'Gatekeeping Project',
    title: 'Traffic × ABM Agency',
    subtitle: 'Drive hyper-targeted traffic with Account-Based Marketing',
    tagline: 'Combine paid traffic with ABM to reach decision makers at your dream accounts',
    description: 'Account-Based Marketing meets performance advertising. Experts build and run ABM campaigns targeting specific companies and personas across LinkedIn Ads, Google Ads, and programmatic channels.',
    badge: 'Enterprise',
    difficulty: 'Advanced',
    duration: '2–4 weeks setup + ongoing',
    subProjects: ['Target Account List Build', 'ABM Campaign Setup', 'Paid Traffic Management'],
    howItWorks: [
      'Build Target Account List (TAL) from ideal customer profile',
      'Set up LinkedIn Matched Audiences and Google Customer Match',
      'Create personalised ad creatives for each account segment',
      'Run retargeting sequences to warm up accounts over time',
      'Track account engagement and pipeline influence',
    ],
    deliverables: [
      'Target Account List (TAL)',
      'ABM campaign strategy document',
      'Ad creatives for each account segment',
      'Weekly performance dashboard',
      'Account engagement report',
    ],
    subjects: ['ABM Strategy', 'Target Account Selection', 'LinkedIn Ads', 'Google Ads', 'Retargeting', 'Account Engagement Tracking'],
    tools: ['LinkedIn Campaign Manager', 'Google Ads', 'Demandbase', '6sense', 'Terminus', 'HubSpot'],
    expertSkills: ['ABM', 'LinkedIn Ads', 'Google Ads', 'Paid Advertising', 'Demandbase', 'Terminus', '6sense'],
    targetFor: ['B2B SaaS', 'Marketing Agencies', 'Enterprise Software'],
    matchIndustries: ['B2B SaaS', 'Technology & Software', 'Marketing', 'Enterprise Software'],
    faq: [
      { q: 'What budget do I need for ads?', a: 'We recommend a minimum ad spend of $2,000/month for LinkedIn and $1,500/month for Google.' },
      { q: 'How many target accounts should I start with?', a: 'Starting with 50–200 target accounts gives you enough data to optimise.' },
      { q: 'How long before pipeline is influenced?', a: 'Expect meaningful pipeline influence signals at the 6–8 week mark.' },
    ],
    successHighlight: '4.1x ROAS on LinkedIn ABM targeting CFOs at 50-company account list for a fintech SaaS',
    successROI: '4.1x ROAS',
    successStory: { company: 'Fintech SaaS', result: '4.1x ROAS on LinkedIn ABM', industry: 'Fintech' },
    stats: {
      expertCount: 11, completedCount: 28, avgRating: 4.6, trendingCount: 9,
      trendingLabel: '9 enterprise campaigns live',
      nearbyExpertCount: { Mumbai: 3, Bangalore: 5, Delhi: 2, Hyderabad: 2, Pune: 1 },
      matchScore: { 'B2B SaaS': 95, 'Technology & Software': 92, 'Marketing': 88, 'Enterprise Software': 97, 'Fintech': 90, 'Healthcare': 60, 'Ecommerce': 65, 'Education': 58 },
    },
    expertCities: ['Bangalore', 'Mumbai', 'Delhi', 'Hyderabad'],
    theme: { gradient: 'from-cyan-500 to-teal-600', bgLight: 'bg-cyan-50', textColor: 'text-cyan-700', borderColor: 'border-cyan-200' },
    budgetRange: '₹50,000 – ₹2,00,000/mo',
    isFeatured: false, isTrending: false,
  },
  {
    slug: 'inbound-traffic',
    category: 'traffic',
    number: 'Hunting Project',
    title: 'Inbound Aggregation',
    subtitle: 'Website traffic & inbound lead aggregation system',
    tagline: 'Capture, qualify, and route inbound traffic from every channel into your pipeline',
    description: 'Build a complete inbound engine: SEO content, conversion rate optimisation, lead magnet creation, and automated lead routing. Experts ensure every visitor who lands on your site has the highest chance of converting.',
    badge: null,
    difficulty: 'Intermediate',
    duration: '3–4 weeks',
    subProjects: ['SEO & Content Funnel', 'CRO & Lead Capture', 'Lead Routing Automation'],
    howItWorks: [
      'Audit current website traffic and conversion points',
      'Build keyword strategy and SEO content plan',
      'Create lead magnets (ebooks, tools, templates)',
      'Set up lead capture forms, chatbots, and landing pages',
      'Build automated lead scoring and routing rules',
    ],
    deliverables: [
      'SEO content calendar (3-month)',
      'Optimised landing pages',
      '2–3 lead magnets',
      'Lead capture & routing automation',
      'Monthly traffic & conversion report',
    ],
    subjects: ['SEO Strategy', 'Content Marketing', 'Conversion Rate Optimisation', 'Lead Magnet Creation', 'Landing Page Design', 'Lead Routing Automation'],
    tools: ['Ahrefs', 'SEMrush', 'Webflow', 'HubSpot', 'Google Analytics', 'Hotjar'],
    expertSkills: ['SEO', 'CRO', 'Content Marketing', 'HubSpot', 'Webflow', 'Google Analytics', 'Lead Generation'],
    targetFor: ['Ecommerce', 'Coaches', 'Course Creators', 'B2B SaaS'],
    matchIndustries: ['Ecommerce', 'Coaching', 'Education', 'B2B SaaS', 'Technology & Software'],
    faq: [
      { q: 'Do you write the SEO content or just the strategy?', a: 'Both — your expert builds the keyword strategy AND writes the content.' },
      { q: 'How fast can I rank on Google?', a: 'New content typically starts gaining traction in 6–12 weeks.' },
      { q: 'What lead magnets work best?', a: 'ROI calculators, industry benchmarks, templates, and free tools convert best.' },
    ],
    successHighlight: '210% organic traffic growth in 90 days for a course creator',
    successROI: '210% traffic growth',
    successStory: { company: 'Course Creator', result: '210% organic traffic growth in 90 days', industry: 'Education' },
    stats: {
      expertCount: 16, completedCount: 57, avgRating: 4.7, trendingCount: 24,
      trendingLabel: '24 new funnels launched this week',
      nearbyExpertCount: { Mumbai: 4, Bangalore: 7, Delhi: 3, Hyderabad: 3, Pune: 3, Chennai: 2 },
      matchScore: { 'Ecommerce': 96, 'Coaching': 93, 'Education': 95, 'B2B SaaS': 87, 'Technology & Software': 82, 'Marketing': 89, 'Professional Services': 78, 'Consulting': 75 },
    },
    expertCities: ['Bangalore', 'Mumbai', 'Delhi', 'Hyderabad', 'Pune', 'Chennai'],
    theme: { gradient: 'from-teal-500 to-cyan-600', bgLight: 'bg-teal-50', textColor: 'text-teal-700', borderColor: 'border-teal-200' },
    budgetRange: '₹20,000 – ₹80,000/mo',
    isFeatured: false, isTrending: true,
  },
  {
    slug: 'intent-social-listening',
    category: 'intelligence',
    number: 'Observation Project',
    title: 'Intent × Social Listening',
    subtitle: 'Listen for buying intent across LinkedIn, Reddit, G2 & Gartner',
    tagline: 'Detect intent signals across social media and review platforms in real time',
    description: 'Monitor buying signals across LinkedIn, Reddit, G2, Gartner Peer Insights, and custom communities. Experts set up automated listening streams that surface prospects actively researching solutions like yours.',
    badge: 'Advanced',
    difficulty: 'Advanced',
    duration: 'Ongoing (monthly)',
    subProjects: ['Intent Signal Setup', 'Social Listening Streams', 'Engagement Workflow'],
    howItWorks: [
      'Map the platforms where your buyers research and hang out',
      'Set up keyword and intent monitoring across each platform',
      'Build scoring model for signal strength and purchase proximity',
      'Create engagement playbooks for each signal type',
      'Deliver weekly intent report with prioritised action items',
    ],
    deliverables: [
      'Intent monitoring dashboard',
      'Weekly buyer signal report',
      'Engagement playbooks per signal type',
      'Automated Slack/CRM alerts',
      'Competitive intelligence summary',
    ],
    subjects: ['Intent Signal Monitoring', 'Social Listening', 'Competitor Intelligence', 'Signal Scoring', 'Reddit & G2 Monitoring', 'Engagement Playbooks'],
    tools: ['Bombora', 'G2 Buyer Intent', 'LinkedIn Sales Nav', 'Reddit API', 'Gartner Peer Insights', 'Slack'],
    expertSkills: ['Social Listening', 'Intent Data', 'Bombora', 'G2', 'LinkedIn', 'Sales Intelligence', 'Automation'],
    targetFor: ['B2B SaaS', 'Marketing Agencies', 'Consultants'],
    matchIndustries: ['B2B SaaS', 'Technology & Software', 'Marketing', 'Consulting'],
    faq: [
      { q: 'What does an "intent signal" actually look like?', a: 'Examples: someone posts on Reddit asking for tool recommendations, a competitor gets a bad review, or a target account browses your G2 category.' },
      { q: 'How do I act on the signals once I get them?', a: 'Your expert builds engagement playbooks — specific response templates for each signal type.' },
      { q: 'Will this work for my niche industry?', a: 'Yes. We customise listening keywords, subreddits, G2 categories, and LinkedIn groups specifically to your ICP.' },
    ],
    successHighlight: '31 warm inbound conversations started in week 1 from Reddit + LinkedIn intent signals',
    successROI: '31 warm convos / week 1',
    successStory: { company: 'B2B SaaS', result: '31 warm conversations in week 1', industry: 'B2B SaaS' },
    stats: {
      expertCount: 8, completedCount: 19, avgRating: 4.8, trendingCount: 8,
      trendingLabel: '8 listening streams active',
      nearbyExpertCount: { Mumbai: 2, Bangalore: 4, Delhi: 2 },
      matchScore: { 'B2B SaaS': 97, 'Technology & Software': 93, 'Marketing': 91, 'Consulting': 88, 'Professional Services': 80, 'Ecommerce': 65, 'Healthcare': 58, 'Education': 55 },
    },
    expertCities: ['Bangalore', 'Mumbai', 'Delhi'],
    theme: { gradient: 'from-blue-600 to-blue-800', bgLight: 'bg-blue-50', textColor: 'text-blue-800', borderColor: 'border-blue-200' },
    isFeatured: false, isTrending: false,
  },
  {
    slug: 'connector-relationship',
    category: 'relationship',
    number: 'Connector Project',
    title: 'Connection & Relationship Manager',
    subtitle: 'Manage inbound & outbound LinkedIn connections on your behalf',
    tagline: 'Accept, respond & warm up connections — on your behalf',
    description: 'A fully managed LinkedIn relationship service. Experts monitor your LinkedIn inbox, accept relevant connection requests, send personalised intro messages, and warm up cold connections through consistent engagement.',
    badge: null,
    difficulty: 'Beginner',
    duration: 'Ongoing (monthly)',
    subProjects: ['Connection Request Management', 'Warm-up Sequences', 'Inbox Management'],
    howItWorks: [
      'Audit your LinkedIn network and define connection criteria',
      'Expert monitors and responds to connection requests daily',
      'Build warm-up message sequences for new connections',
      "Engage with target accounts' posts to stay visible",
      'Weekly report on new connections and conversations started',
    ],
    deliverables: [
      '50–200 new qualified connections/month',
      'Personalised outreach templates',
      'LinkedIn inbox management',
      'Warm-up engagement schedule',
      'Weekly connection & conversation report',
    ],
    subjects: ['LinkedIn Strategy', 'Connection Management', 'Warm-up Sequences', 'Inbox Management', 'Social Selling', 'Relationship Tracking'],
    tools: ['LinkedIn Sales Navigator', 'Dripify', 'HubSpot CRM', 'Notion', 'PhantomBuster', 'Slack'],
    expertSkills: ['LinkedIn', 'Social Selling', 'Copywriting', 'CRM', 'Relationship Building'],
    targetFor: ['Coaches', 'Consultants', 'Professional Services', 'B2B SaaS'],
    matchIndustries: ['Coaching', 'Consulting', 'Professional Services', 'B2B SaaS', 'Technology & Software'],
    faq: [
      { q: 'Is this safe for my LinkedIn account?', a: 'Yes. We operate within LinkedIn\'s limits using human-in-the-loop workflows, not bots.' },
      { q: 'Do I give you access to my account?', a: 'You share a managed login via a secure password manager. Activity is fully transparent.' },
      { q: 'What types of connections will you target?', a: 'You define the ICP during onboarding. The expert targets only connections matching your criteria.' },
    ],
    successHighlight: '180 new targeted LinkedIn connections in 30 days — 14 converted to discovery calls',
    successROI: '14 discovery calls / month',
    successStory: { company: 'Consultant', result: '14 discovery calls from 180 LinkedIn connections in 30 days', industry: 'Consulting' },
    stats: {
      expertCount: 20, completedCount: 78, avgRating: 4.8, trendingCount: 19,
      trendingLabel: '19 consultants enrolled this month',
      nearbyExpertCount: { Mumbai: 6, Bangalore: 8, Delhi: 4, Hyderabad: 3, Pune: 4, Chennai: 3, Kolkata: 2 },
      matchScore: { 'Coaching': 96, 'Consulting': 95, 'Professional Services': 94, 'B2B SaaS': 89, 'Technology & Software': 83, 'Marketing': 85, 'Ecommerce': 72, 'Education': 78 },
    },
    expertCities: ['Mumbai', 'Bangalore', 'Delhi', 'Pune', 'Hyderabad', 'Chennai', 'Kolkata'],
    theme: { gradient: 'from-pink-500 to-rose-600', bgLight: 'bg-pink-50', textColor: 'text-pink-700', borderColor: 'border-pink-200' },
    isFeatured: false, isTrending: false,
  },
  {
    slug: 'demo-prep-crm',
    category: 'intelligence',
    number: 'Preparation Project',
    title: 'Demo Prep & CRM Research Brief',
    subtitle: 'For each scheduled demo, get a CRM-ready research brief',
    tagline: 'Know everything about your prospect before the call — automatically',
    description: 'Before every demo or sales call, get a structured research brief: company profile, recent news, identified pain points, tech stack, decision makers, LinkedIn activity, and talking points — delivered to your CRM.',
    badge: 'New',
    difficulty: 'Intermediate',
    duration: 'Per demo or ongoing',
    subProjects: ['Company Research Automation', 'Pain Point Identification', 'CRM Note Delivery'],
    howItWorks: [
      'Trigger fires when demo is booked in your calendar or CRM',
      'Expert or AI researches the company and key stakeholders',
      'Pain points identified from job listings, reviews, and news',
      'Research brief formatted and pushed to CRM deal record',
      'Sales rep receives Slack alert with brief 30 mins before call',
    ],
    deliverables: [
      'Structured company profile per prospect',
      'Key stakeholder LinkedIn profiles',
      'Pain points and talking points',
      'Recent news and intent triggers',
      'CRM note + Slack notification',
    ],
    subjects: ['Company Research', 'Stakeholder Profiling', 'Pain Point Analysis', 'Tech Stack Identification', 'CRM Automation', 'Pre-call Intelligence'],
    tools: ['HubSpot', 'Salesforce', 'Clay', 'Firecrawl', 'LinkedIn Sales Nav', 'Calendly'],
    expertSkills: ['Sales Research', 'CRM', 'HubSpot', 'Salesforce', 'Sales Intelligence', 'Automation'],
    targetFor: ['B2B SaaS', 'Professional Services', 'Marketing Agencies'],
    matchIndustries: ['B2B SaaS', 'Technology & Software', 'Professional Services', 'Marketing', 'Consulting'],
    faq: [
      { q: 'How long does one research brief take?', a: 'Standard briefs take 30–60 minutes per prospect. Deep-dive briefs with competitive analysis take 90–120 minutes.' },
      { q: 'Can this work with any CRM?', a: 'Yes. We support HubSpot, Salesforce, Pipedrive, and most other CRMs via Zapier/Make.' },
      { q: 'What if my sales team has 10 demos a week?', a: 'We scale with you. Volume pricing applies above 20 briefs/month.' },
    ],
    successHighlight: 'Sales team win rate jumped from 22% to 38% in Q1 after implementing pre-call research briefs',
    successROI: '+16% win rate',
    successStory: { company: 'B2B Sales Team', result: 'Win rate from 22% to 38% in Q1', industry: 'B2B SaaS' },
    stats: {
      expertCount: 12, completedCount: 43, avgRating: 4.9, trendingCount: 15,
      trendingLabel: '15 teams using automated prep',
      nearbyExpertCount: { Mumbai: 3, Bangalore: 5, Delhi: 2, Hyderabad: 2, Pune: 2 },
      matchScore: { 'B2B SaaS': 94, 'Technology & Software': 90, 'Professional Services': 92, 'Marketing': 85, 'Consulting': 89, 'Ecommerce': 65, 'Healthcare': 70, 'Education': 62 },
    },
    expertCities: ['Bangalore', 'Mumbai', 'Delhi', 'Hyderabad', 'Pune'],
    theme: { gradient: 'from-amber-500 to-orange-500', bgLight: 'bg-amber-50', textColor: 'text-amber-700', borderColor: 'border-amber-200' },
    isFeatured: false, isTrending: false,
  },
  {
    slug: 'call-intelligence-crm',
    category: 'intelligence',
    number: 'Listening Project',
    title: 'Call Intelligence × CRM',
    subtitle: 'Post-call intelligence: AI transcription, insights & CRM updates',
    tagline: 'Every sales call becomes structured data, coaching insights, and pipeline actions',
    description: 'Transform your post-call workflow. Experts set up AI call recording and transcription, extract deal intelligence, auto-update your CRM, and surface coaching insights for your team.',
    badge: null,
    difficulty: 'Advanced',
    duration: '1 week setup + ongoing',
    subProjects: ['Call Recording & Transcription', 'CRM Auto-Update', 'Coaching & Analytics'],
    howItWorks: [
      'Connect call recording tool (Gong / Chorus / Fireflies)',
      'AI transcribes and tags every call automatically',
      'Key insights extracted: objections, next steps, competitors',
      'CRM deal record updated with call summary and tasks',
      'Manager receives weekly coaching report by rep',
    ],
    deliverables: [
      'Call recording + transcription setup',
      'AI insight extraction workflow',
      'Automated CRM update rules',
      'Weekly coaching report template',
      'Deal risk scoring from call signals',
    ],
    subjects: ['Call Recording Setup', 'AI Transcription', 'Deal Intelligence Extraction', 'CRM Auto-Update', 'Coaching Analytics', 'Pipeline Risk Scoring'],
    tools: ['Gong', 'Chorus', 'Fireflies.ai', 'HubSpot', 'Salesforce', 'Slack'],
    expertSkills: ['Gong', 'Chorus', 'Fireflies', 'CRM', 'Salesforce', 'HubSpot', 'Revenue Intelligence'],
    targetFor: ['B2B SaaS', 'Marketing Agencies', 'Professional Services'],
    matchIndustries: ['B2B SaaS', 'Technology & Software', 'Professional Services', 'Marketing'],
    faq: [
      { q: 'Do I need Gong specifically?', a: 'No. We work with Gong, Chorus, Fireflies, Otter.ai, or any recording tool you already use.' },
      { q: 'Can it identify competitor mentions automatically?', a: 'Yes. The system flags any mention of competitor names with timestamps.' },
      { q: 'Is call recording legal?', a: 'Laws vary by region. Your expert will configure appropriate consent flows before going live.' },
    ],
    successHighlight: 'Deal slippage reduced by 35% after call intelligence surfaced at-risk signals automatically',
    successROI: '35% less deal slippage',
    successStory: { company: 'SaaS Sales Team', result: '35% reduction in deal slippage', industry: 'B2B SaaS' },
    stats: {
      expertCount: 7, completedCount: 22, avgRating: 4.7, trendingCount: 7,
      trendingLabel: '7 sales teams onboarded',
      nearbyExpertCount: { Mumbai: 2, Bangalore: 3, Delhi: 2 },
      matchScore: { 'B2B SaaS': 92, 'Technology & Software': 88, 'Professional Services': 87, 'Marketing': 83, 'Consulting': 80, 'Ecommerce': 60, 'Healthcare': 65, 'Education': 58 },
    },
    expertCities: ['Bangalore', 'Mumbai', 'Delhi'],
    theme: { gradient: 'from-slate-500 to-slate-700', bgLight: 'bg-slate-50', textColor: 'text-slate-700', borderColor: 'border-slate-200' },
    isFeatured: false, isTrending: false,
  },
  {
    slug: 'virtual-assistant-marketing',
    category: 'assistant',
    number: 'Project 4',
    title: 'Marketing Virtual Assistant',
    subtitle: 'Pre-trained AI-powered virtual assistants for business growth',
    tagline: 'Handle social media, emails, inbox, tech and more — trained to build your business online',
    description: 'A Karya-trained virtual assistant equipped with a personalised DoingBlueprint — a structured plan defining exactly what needs to be done, in what order, and what "done" looks like.',
    badge: 'Most Hired',
    difficulty: 'Beginner',
    duration: 'Ongoing (full-time or part-time)',
    subProjects: ['Social Media VA', 'Email & Inbox VA', 'Tech & Automation VA'],
    howItWorks: [
      'Discovery call: map your recurring tasks and priorities',
      'Build your DoingBlueprint (tasks, order, definition of done)',
      'Match you with a pre-trained VA from our vetted roster',
      'VA starts executing from blueprint on Day 1',
      'Weekly check-in and blueprint refinement',
    ],
    deliverables: [
      'Personalised DoingBlueprint document',
      'Dedicated VA with relevant tool training',
      'Weekly task completion report',
      'SOP library built over time',
      'Escalation process for edge cases',
    ],
    subjects: ['DoingBlueprint Creation', 'Social Media Management', 'Email & Inbox Management', 'Content Scheduling', 'Admin & Operations', 'Tech & Automation'],
    tools: ['Notion', 'Canva', 'Buffer', 'Zapier', 'Google Workspace', 'Slack'],
    expertSkills: ['Social Media', 'Email Management', 'Content Scheduling', 'Canva', 'Notion', 'Zapier', 'Admin'],
    targetFor: ['Coaches', 'Course Creators', 'Consultants', 'Ecommerce', 'Professional Services'],
    matchIndustries: ['Coaching', 'Education', 'Ecommerce', 'Consulting', 'Professional Services'],
    faq: [
      { q: 'What is a DoingBlueprint?', a: 'A DoingBlueprint is a structured document defining every recurring task, the order to do them, the tools to use, and what "done" looks like.' },
      { q: 'Is the VA full-time or part-time?', a: 'Both options available — 20hrs/week (part-time) or 40hrs/week (full-time). Hours are tracked transparently.' },
      { q: 'What if the VA is not a good fit?', a: 'We offer a free replacement within the first 14 days. After that, replacements are handled within 48 hours.' },
    ],
    successHighlight: '22 hours/week saved for a course creator — content, emails, and community managed end-to-end',
    successROI: '22 hrs/week saved',
    successStory: { company: 'Course Creator', result: '22 hours/week freed up', industry: 'Education' },
    stats: {
      expertCount: 35, completedCount: 142, avgRating: 4.8, trendingCount: 71,
      trendingLabel: '71 VAs matched this week',
      nearbyExpertCount: { Mumbai: 10, Bangalore: 12, Delhi: 8, Hyderabad: 6, Pune: 7, Chennai: 5, Kolkata: 4, Ahmedabad: 3, Jaipur: 2 },
      matchScore: { 'Coaching': 97, 'Education': 96, 'Ecommerce': 94, 'Consulting': 92, 'Professional Services': 93, 'Marketing': 89, 'B2B SaaS': 82, 'Technology & Software': 78 },
    },
    expertCities: ['Mumbai', 'Bangalore', 'Delhi', 'Hyderabad', 'Pune', 'Chennai', 'Kolkata', 'Ahmedabad', 'Jaipur'],
    theme: { gradient: 'from-emerald-500 to-green-600', bgLight: 'bg-emerald-50', textColor: 'text-emerald-700', borderColor: 'border-emerald-200' },
    isFeatured: true, isTrending: true,
  },
  {
    slug: 'ai-expert-matching',
    category: 'ai-matching',
    number: 'Project 5.XX',
    title: 'AI Expert Finder & Negotiator',
    subtitle: "The AI agent that finds, vets & negotiates with India's top 5% experts",
    tagline: 'Find, vet, and negotiate with AI-powered fractional experts and agencies at scale',
    description: "Stop spending weeks sourcing freelancers. Our AI agent searches Karya's network of top 5% AI-powered fractional experts and agencies, automatically vets them against your requirements, and handles initial negotiation.",
    badge: 'AI-Powered',
    difficulty: 'Beginner',
    duration: '48–72 hours',
    subProjects: ['AI-Powered Talent Search', 'Automated Vetting', 'Negotiation & Onboarding'],
    howItWorks: [
      'Submit your project brief (role, skills, budget, timeline)',
      'AI searches and scores 500+ expert profiles',
      'Top 10 candidates auto-vetted against your criteria',
      'AI handles initial outreach and negotiation',
      'You receive 3 final candidates with proposals',
    ],
    deliverables: [
      '3 vetted expert proposals',
      'Skill match scores and work samples',
      'Negotiated rate within your budget',
      'Onboarding checklist for chosen expert',
      'Replacement guarantee (30 days)',
    ],
    subjects: ['Requirements Analysis', 'AI Talent Search', 'Automated Vetting', 'Skill Matching', 'Rate Negotiation', 'Expert Onboarding'],
    tools: ['Karya-AI Platform', 'LinkedIn', 'GitHub', 'Portfolio Review', 'Video Interview', 'Contract Management'],
    expertSkills: ['Talent Sourcing', 'Technical Assessment', 'Negotiation', 'Project Management', 'AI Tools'],
    targetFor: ['B2B SaaS', 'Marketing Agencies', 'Ecommerce', 'Professional Services', 'Coaches'],
    matchIndustries: ['B2B SaaS', 'Marketing', 'Ecommerce', 'Technology & Software', 'Professional Services', 'Coaching', 'Consulting'],
    faq: [
      { q: 'How is this different from just browsing the Expert Marketplace?', a: 'The AI Finder is fully managed — you submit a brief and receive 3 pre-vetted candidates with negotiated rates within 72 hours.' },
      { q: 'What is the platform fee?', a: 'The search is free. When you hire, a one-time 10% fee applies to the first month\'s invoice.' },
      { q: 'What is the replacement guarantee?', a: 'If your hired expert does not deliver within the first 30 days, we source a replacement at zero cost.' },
    ],
    successHighlight: 'Full-stack growth team of 4 assembled in 72 hours — agency avoided 6 weeks of sourcing',
    successROI: '6 weeks saved on hiring',
    successStory: { company: 'Marketing Agency', result: 'Growth team of 4 assembled in 72 hours', industry: 'Marketing' },
    stats: {
      expertCount: 5, completedCount: 67, avgRating: 4.9, trendingCount: 29,
      trendingLabel: '29 matches made this week',
      nearbyExpertCount: { Mumbai: 2, Bangalore: 2, Delhi: 1, Hyderabad: 1, Pune: 1 },
      matchScore: { 'B2B SaaS': 90, 'Marketing': 92, 'Ecommerce': 88, 'Technology & Software': 85, 'Professional Services': 88, 'Coaching': 90, 'Consulting': 91, 'Education': 82 },
    },
    expertCities: ['Mumbai', 'Bangalore', 'Delhi', 'Hyderabad', 'Pune', 'Chennai', 'Kolkata', 'Ahmedabad'],
    theme: { gradient: 'from-violet-600 to-blue-600', bgLight: 'bg-violet-50', textColor: 'text-violet-700', borderColor: 'border-violet-200' },
    isFeatured: false, isTrending: true,
  },
];


// ── 2. PRICING TIERS PER PROJECT ───────────────────────────────────────────────
// Returns 4 tier objects for a given project _id and slug

function buildPricingTiers(projectId, slug) {
  // Each project category gets different quantity fields + pricing
  const tiersMap = {

    'outbound-list-builder': [
      { tierId: 'credit',  name: 'Credit Only', displayOrder: 1, popular: false, badge: 'Free Start',
        price: { amount: 0,      currency: 'INR', billingCycle: 'free',    label: 'Free',         note: 'Uses platform credits' },
        quantities: { contacts: 50,   revisionRounds: 1 },
        features: { decisionMakerProfiles: false, companyIntelligence: false, icpScoring: false, linkedinProfiles: false, techStackData: false, crmExport: true,  emailVerified: false, dedicatedPM: false, weeklyReport: false },
        support: { type: 'email', label: 'Email Support', responseTime: '48 hours' },
        deliverableSummary: '50 sample contacts — CSV export' },

      { tierId: 'bronze',  name: 'Bronze', displayOrder: 2, popular: false, badge: 'Starter',
        price: { amount: 15000,  currency: 'INR', billingCycle: 'one-time', label: '₹15,000',      note: 'One-time delivery' },
        quantities: { contacts: 300,  revisionRounds: 1 },
        features: { decisionMakerProfiles: true,  companyIntelligence: false, icpScoring: false, linkedinProfiles: true,  techStackData: false, crmExport: true,  emailVerified: true,  dedicatedPM: false, weeklyReport: false },
        support: { type: 'chat', label: 'Chat Support', responseTime: '24 hours' },
        deliverableSummary: '300 verified contacts + LinkedIn profiles + CRM export' },

      { tierId: 'silver',  name: 'Silver',  displayOrder: 3, popular: true,  badge: 'Most Popular',
        price: { amount: 35000,  currency: 'INR', billingCycle: 'one-time', label: '₹35,000',      note: 'One-time delivery' },
        quantities: { contacts: 750,  revisionRounds: 2 },
        features: { decisionMakerProfiles: true,  companyIntelligence: true,  icpScoring: true,  linkedinProfiles: true,  techStackData: false, crmExport: true,  emailVerified: true,  dedicatedPM: false, weeklyReport: true,  abTesting: false },
        support: { type: 'priority-chat', label: 'Priority Chat', responseTime: '4 hours' },
        deliverableSummary: '750 verified contacts + ICP scores + company intel + CRM export' },

      { tierId: 'gold',    name: 'Gold',    displayOrder: 4, popular: false, badge: 'Premium',
        price: { amount: 75000,  currency: 'INR', billingCycle: 'one-time', label: '₹75,000',      note: 'One-time delivery' },
        quantities: { contacts: 1200, revisionRounds: 3 },
        features: { decisionMakerProfiles: true,  companyIntelligence: true,  icpScoring: true,  linkedinProfiles: true,  techStackData: true,  crmExport: true,  emailVerified: true,  dedicatedPM: true,  weeklyReport: true,  intentData: true },
        support: { type: 'dedicated-pm', label: 'Dedicated PM', responseTime: '1 hour' },
        deliverableSummary: '1200 contacts + full intel + tech stack + ICP scoring + dedicated PM' },
    ],

    'sales-outreach-automation': [
      { tierId: 'credit',  name: 'Credit Only', displayOrder: 1, popular: false, badge: 'Free Start',
        price: { amount: 0,      currency: 'INR', billingCycle: 'free',    label: 'Free',         note: 'Uses platform credits' },
        quantities: { emailSequences: 1, revisionRounds: 1 },
        features: { decisionMakerProfiles: false, companyIntelligence: false, icpScoring: false, linkedinProfiles: false, crmExport: false, emailVerified: false, abTesting: false, dedicatedPM: false, weeklyReport: false },
        support: { type: 'email', label: 'Email Support', responseTime: '48 hours' },
        deliverableSummary: '1 email sequence (3 touchpoints) — template only' },

      { tierId: 'bronze',  name: 'Bronze', displayOrder: 2, popular: false, badge: 'Starter',
        price: { amount: 20000,  currency: 'INR', billingCycle: 'one-time', label: '₹20,000',      note: 'One-time setup' },
        quantities: { emailSequences: 2, revisionRounds: 1 },
        features: { crmExport: true, emailVerified: true, abTesting: false, dedicatedPM: false, weeklyReport: false, linkedinProfiles: true },
        support: { type: 'chat', label: 'Chat Support', responseTime: '24 hours' },
        deliverableSummary: '2 sequences (5 touchpoints each) + CRM setup + LinkedIn templates' },

      { tierId: 'silver',  name: 'Silver',  displayOrder: 3, popular: true,  badge: 'Most Popular',
        price: { amount: 45000,  currency: 'INR', billingCycle: 'one-time', label: '₹45,000',      note: 'One-time setup' },
        quantities: { emailSequences: 5, revisionRounds: 2 },
        features: { crmExport: true, emailVerified: true, abTesting: true,  dedicatedPM: false, weeklyReport: true, linkedinProfiles: true, icpScoring: true },
        support: { type: 'priority-chat', label: 'Priority Chat', responseTime: '4 hours' },
        deliverableSummary: '5 sequences + A/B testing + CRM + LinkedIn + weekly reporting' },

      { tierId: 'gold',    name: 'Gold',    displayOrder: 4, popular: false, badge: 'Full Stack',
        price: { amount: 90000,  currency: 'INR', billingCycle: 'one-time', label: '₹90,000',      note: 'One-time setup' },
        quantities: { emailSequences: 10, revisionRounds: 3 },
        features: { crmExport: true, emailVerified: true, abTesting: true,  dedicatedPM: true,  weeklyReport: true, linkedinProfiles: true, icpScoring: true, intentData: true },
        support: { type: 'dedicated-pm', label: 'Dedicated PM', responseTime: '1 hour' },
        deliverableSummary: 'Full multi-channel stack — unlimited sequences, PM included, intent data' },
    ],

    'ai-email-sales-agency': [
      { tierId: 'credit',  name: 'Credit Only', displayOrder: 1, popular: false, badge: 'Free Trial',
        price: { amount: 0,       currency: 'INR', billingCycle: 'free',    label: 'Free',          note: '7-day trial' },
        quantities: { emailSequences: 1, revisionRounds: 0 },
        features: { emailVerified: false, abTesting: false, dedicatedPM: false, weeklyReport: false },
        support: { type: 'email', label: 'Email Support', responseTime: '48 hours' },
        deliverableSummary: '7-day trial campaign — 1 domain, limited volume' },

      { tierId: 'bronze',  name: 'Bronze', displayOrder: 2, popular: false, badge: 'Starter',
        price: { amount: 40000,   currency: 'INR', billingCycle: 'monthly', label: '₹40,000/mo',    note: 'Per month' },
        quantities: { emailSequences: 2, revisionRounds: 1 },
        features: { emailVerified: true,  abTesting: false, dedicatedPM: false, weeklyReport: true  },
        support: { type: 'chat', label: 'Chat Support', responseTime: '24 hours' },
        deliverableSummary: '500 emails/day · 1 sending domain · basic AI reply handling' },

      { tierId: 'silver',  name: 'Silver',  displayOrder: 3, popular: true,  badge: 'Most Popular',
        price: { amount: 80000,   currency: 'INR', billingCycle: 'monthly', label: '₹80,000/mo',    note: 'Per month' },
        quantities: { emailSequences: 5, revisionRounds: 2 },
        features: { emailVerified: true,  abTesting: true,  dedicatedPM: false, weeklyReport: true  },
        support: { type: 'priority-chat', label: 'Priority Chat', responseTime: '4 hours' },
        deliverableSummary: '2000 emails/day · 3 domains · AI reply + qualification · weekly report' },

      { tierId: 'gold',    name: 'Gold',    displayOrder: 4, popular: false, badge: 'Full Agency',
        price: { amount: 150000,  currency: 'INR', billingCycle: 'monthly', label: '₹1,50,000/mo',  note: 'Per month' },
        quantities: { emailSequences: 10, revisionRounds: 3 },
        features: { emailVerified: true,  abTesting: true,  dedicatedPM: true,  weeklyReport: true, intentData: true },
        support: { type: 'dedicated-pm', label: 'Dedicated PM + Voice Agent', responseTime: '1 hour' },
        deliverableSummary: '5000 emails/day · 5 domains · AI + voice agent handoff · dedicated PM' },
    ],

    'brand-voice-social': [
      { tierId: 'credit',  name: 'Credit Only', displayOrder: 1, popular: false, badge: 'Free Audit',
        price: { amount: 0,      currency: 'INR', billingCycle: 'free',    label: 'Free',         note: 'Brand audit only' },
        quantities: { postsPerMonth: 0, revisionRounds: 0 },
        features: { dedicatedPM: false, weeklyReport: false },
        support: { type: 'email', label: 'Email Support', responseTime: '48 hours' },
        deliverableSummary: 'Brand voice audit document — no posting included' },

      { tierId: 'bronze',  name: 'Bronze', displayOrder: 2, popular: false, badge: 'Starter',
        price: { amount: 15000,  currency: 'INR', billingCycle: 'monthly', label: '₹15,000/mo',   note: 'Per month' },
        quantities: { postsPerMonth: 8, revisionRounds: 1 },
        features: { dedicatedPM: false, weeklyReport: false },
        support: { type: 'chat', label: 'Chat Support', responseTime: '24 hours' },
        deliverableSummary: '8 LinkedIn posts/month · content calendar · brand voice doc' },

      { tierId: 'silver',  name: 'Silver',  displayOrder: 3, popular: true,  badge: 'Most Popular',
        price: { amount: 30000,  currency: 'INR', billingCycle: 'monthly', label: '₹30,000/mo',   note: 'Per month' },
        quantities: { postsPerMonth: 16, revisionRounds: 2 },
        features: { dedicatedPM: false, weeklyReport: true  },
        support: { type: 'priority-chat', label: 'Priority Chat', responseTime: '4 hours' },
        deliverableSummary: '16 posts/month · LinkedIn + X · community engagement · analytics' },

      { tierId: 'gold',    name: 'Gold',    displayOrder: 4, popular: false, badge: 'Multi-Platform',
        price: { amount: 60000,  currency: 'INR', billingCycle: 'monthly', label: '₹60,000/mo',   note: 'Per month' },
        quantities: { postsPerMonth: 28, revisionRounds: 3 },
        features: { dedicatedPM: true,  weeklyReport: true  },
        support: { type: 'dedicated-pm', label: 'Dedicated Strategist', responseTime: '2 hours' },
        deliverableSummary: '28 posts/month · LinkedIn + X + Communities · dedicated content strategist' },
    ],

    'traffic-abm': [
      { tierId: 'credit',  name: 'Credit Only', displayOrder: 1, popular: false, badge: 'Free Audit',
        price: { amount: 0,       currency: 'INR', billingCycle: 'free',    label: 'Free',          note: 'TAL audit only' },
        quantities: { contacts: 0, revisionRounds: 0 },
        features: { dedicatedPM: false, weeklyReport: false },
        support: { type: 'email', label: 'Email Support', responseTime: '48 hours' },
        deliverableSummary: 'Target Account List audit — strategy only, no campaigns' },

      { tierId: 'bronze',  name: 'Bronze', displayOrder: 2, popular: false, badge: 'Starter',
        price: { amount: 50000,   currency: 'INR', billingCycle: 'monthly', label: '₹50,000/mo',    note: '+ ad spend' },
        quantities: { contacts: 50,  revisionRounds: 1 },
        features: { dedicatedPM: false, weeklyReport: true  },
        support: { type: 'chat', label: 'Chat Support', responseTime: '24 hours' },
        deliverableSummary: '50 target accounts · LinkedIn Ads only · weekly performance report' },

      { tierId: 'silver',  name: 'Silver',  displayOrder: 3, popular: true,  badge: 'Most Popular',
        price: { amount: 100000,  currency: 'INR', billingCycle: 'monthly', label: '₹1,00,000/mo',  note: '+ ad spend' },
        quantities: { contacts: 200, revisionRounds: 2 },
        features: { dedicatedPM: false, weeklyReport: true, intentData: true },
        support: { type: 'priority-chat', label: 'Priority Chat', responseTime: '4 hours' },
        deliverableSummary: '200 accounts · LinkedIn + Google · intent data · bi-weekly strategy calls' },

      { tierId: 'gold',    name: 'Gold',    displayOrder: 4, popular: false, badge: 'Enterprise',
        price: { amount: 200000,  currency: 'INR', billingCycle: 'monthly', label: '₹2,00,000/mo',  note: '+ ad spend' },
        quantities: { contacts: 500, revisionRounds: 3 },
        features: { dedicatedPM: true,  weeklyReport: true, intentData: true  },
        support: { type: 'dedicated-pm', label: 'Dedicated ABM Manager', responseTime: '1 hour' },
        deliverableSummary: '500 accounts · full multi-channel ABM · dedicated manager · pipeline reporting' },
    ],

    'inbound-traffic': [
      { tierId: 'credit',  name: 'Credit Only', displayOrder: 1, popular: false, badge: 'Free Audit',
        price: { amount: 0,      currency: 'INR', billingCycle: 'free',    label: 'Free',         note: 'SEO audit only' },
        quantities: { revisionRounds: 0 },
        features: { dedicatedPM: false, weeklyReport: false },
        support: { type: 'email', label: 'Email Support', responseTime: '48 hours' },
        deliverableSummary: 'SEO & conversion audit — no deliverables, analysis only' },

      { tierId: 'bronze',  name: 'Bronze', displayOrder: 2, popular: false, badge: 'Starter',
        price: { amount: 20000,  currency: 'INR', billingCycle: 'one-time', label: '₹20,000',      note: 'One-time project' },
        quantities: { revisionRounds: 1 },
        features: { dedicatedPM: false, weeklyReport: false },
        support: { type: 'chat', label: 'Chat Support', responseTime: '24 hours' },
        deliverableSummary: '4 SEO content pieces · 1 landing page · basic lead capture' },

      { tierId: 'silver',  name: 'Silver',  displayOrder: 3, popular: true,  badge: 'Most Popular',
        price: { amount: 40000,  currency: 'INR', billingCycle: 'one-time', label: '₹40,000',      note: 'One-time project' },
        quantities: { revisionRounds: 2 },
        features: { dedicatedPM: false, weeklyReport: true  },
        support: { type: 'priority-chat', label: 'Priority Chat', responseTime: '4 hours' },
        deliverableSummary: '10 content pieces · 3 landing pages · 2 lead magnets · routing automation' },

      { tierId: 'gold',    name: 'Gold',    displayOrder: 4, popular: false, badge: 'Full Funnel',
        price: { amount: 80000,  currency: 'INR', billingCycle: 'one-time', label: '₹80,000',      note: 'One-time project' },
        quantities: { revisionRounds: 3 },
        features: { dedicatedPM: true,  weeklyReport: true  },
        support: { type: 'dedicated-pm', label: 'Dedicated PM', responseTime: '2 hours' },
        deliverableSummary: '20 content pieces · full funnel · 3 lead magnets · complete automation + PM' },
    ],

    'intent-social-listening': [
      { tierId: 'credit',  name: 'Credit Only', displayOrder: 1, popular: false, badge: 'Free Trial',
        price: { amount: 0,      currency: 'INR', billingCycle: 'free',    label: 'Free',         note: '14-day trial' },
        quantities: { reportsPerMonth: 0, revisionRounds: 0 },
        features: { dedicatedPM: false, weeklyReport: false },
        support: { type: 'email', label: 'Email Support', responseTime: '48 hours' },
        deliverableSummary: '14-day listening trial on 1 platform — sample report' },

      { tierId: 'bronze',  name: 'Bronze', displayOrder: 2, popular: false, badge: 'Starter',
        price: { amount: 15000,  currency: 'INR', billingCycle: 'monthly', label: '₹15,000/mo',   note: 'Per month' },
        quantities: { reportsPerMonth: 4, revisionRounds: 1 },
        features: { dedicatedPM: false, weeklyReport: true  },
        support: { type: 'chat', label: 'Chat Support', responseTime: '24 hours' },
        deliverableSummary: '3 platforms monitored · weekly signal report · Slack alerts' },

      { tierId: 'silver',  name: 'Silver',  displayOrder: 3, popular: true,  badge: 'Most Popular',
        price: { amount: 30000,  currency: 'INR', billingCycle: 'monthly', label: '₹30,000/mo',   note: 'Per month' },
        quantities: { reportsPerMonth: 8, revisionRounds: 2 },
        features: { dedicatedPM: false, weeklyReport: true, intentData: true  },
        support: { type: 'priority-chat', label: 'Priority Chat', responseTime: '4 hours' },
        deliverableSummary: '6 platforms · daily alerts · engagement playbooks · CRM integration' },

      { tierId: 'gold',    name: 'Gold',    displayOrder: 4, popular: false, badge: 'Full Intel',
        price: { amount: 60000,  currency: 'INR', billingCycle: 'monthly', label: '₹60,000/mo',   note: 'Per month' },
        quantities: { reportsPerMonth: 12, revisionRounds: 3 },
        features: { dedicatedPM: true,  weeklyReport: true, intentData: true, companyIntelligence: true },
        support: { type: 'dedicated-pm', label: 'Dedicated Analyst', responseTime: '2 hours' },
        deliverableSummary: 'All platforms · competitor intel · daily briefs · dedicated analyst' },
    ],

    'connector-relationship': [
      { tierId: 'credit',  name: 'Credit Only', displayOrder: 1, popular: false, badge: 'Free Audit',
        price: { amount: 0,      currency: 'INR', billingCycle: 'free',    label: 'Free',         note: 'Profile audit only' },
        quantities: { contacts: 0, revisionRounds: 0 },
        features: { dedicatedPM: false, weeklyReport: false },
        support: { type: 'email', label: 'Email Support', responseTime: '48 hours' },
        deliverableSummary: 'LinkedIn profile audit + ICP targeting plan' },

      { tierId: 'bronze',  name: 'Bronze', displayOrder: 2, popular: false, badge: 'Starter',
        price: { amount: 10000,  currency: 'INR', billingCycle: 'monthly', label: '₹10,000/mo',   note: 'Per month' },
        quantities: { contacts: 50,  revisionRounds: 1 },
        features: { dedicatedPM: false, weeklyReport: false },
        support: { type: 'chat', label: 'Chat Support', responseTime: '24 hours' },
        deliverableSummary: '50 new connections/month · connection templates · basic management' },

      { tierId: 'silver',  name: 'Silver',  displayOrder: 3, popular: true,  badge: 'Most Popular',
        price: { amount: 20000,  currency: 'INR', billingCycle: 'monthly', label: '₹20,000/mo',   note: 'Per month' },
        quantities: { contacts: 150, revisionRounds: 2 },
        features: { dedicatedPM: false, weeklyReport: true  },
        support: { type: 'priority-chat', label: 'Priority Chat', responseTime: '4 hours' },
        deliverableSummary: '150 connections/month · warm-up sequences · inbox management · weekly report' },

      { tierId: 'gold',    name: 'Gold',    displayOrder: 4, popular: false, badge: 'Full Management',
        price: { amount: 35000,  currency: 'INR', billingCycle: 'monthly', label: '₹35,000/mo',   note: 'Per month' },
        quantities: { contacts: 300, revisionRounds: 3 },
        features: { dedicatedPM: true,  weeklyReport: true  },
        support: { type: 'dedicated-pm', label: 'Dedicated Manager', responseTime: '2 hours' },
        deliverableSummary: '300+ connections · full inbox management · CRM sync · dedicated manager' },
    ],

    'demo-prep-crm': [
      { tierId: 'credit',  name: 'Credit Only', displayOrder: 1, popular: false, badge: 'Free Trial',
        price: { amount: 0,      currency: 'INR', billingCycle: 'free',    label: 'Free',         note: '3 briefs trial' },
        quantities: { reportsPerMonth: 3, revisionRounds: 0 },
        features: { dedicatedPM: false, weeklyReport: false },
        support: { type: 'email', label: 'Email Support', responseTime: '48 hours' },
        deliverableSummary: '3 free research briefs — basic company profile only' },

      { tierId: 'bronze',  name: 'Bronze', displayOrder: 2, popular: false, badge: 'Starter',
        price: { amount: 8000,   currency: 'INR', billingCycle: 'monthly', label: '₹8,000/mo',    note: 'Up to 10 briefs' },
        quantities: { reportsPerMonth: 10, revisionRounds: 1 },
        features: { dedicatedPM: false, weeklyReport: false, crmExport: true  },
        support: { type: 'chat', label: 'Chat Support', responseTime: '24 hours' },
        deliverableSummary: '10 briefs/month · company + stakeholder profile · CRM note' },

      { tierId: 'silver',  name: 'Silver',  displayOrder: 3, popular: true,  badge: 'Most Popular',
        price: { amount: 18000,  currency: 'INR', billingCycle: 'monthly', label: '₹18,000/mo',   note: 'Up to 25 briefs' },
        quantities: { reportsPerMonth: 25, revisionRounds: 2 },
        features: { dedicatedPM: false, weeklyReport: true,  crmExport: true, companyIntelligence: true },
        support: { type: 'priority-chat', label: 'Priority Chat', responseTime: '4 hours' },
        deliverableSummary: '25 deep briefs/month · pain points + tech stack + Slack alert + CRM note' },

      { tierId: 'gold',    name: 'Gold',    displayOrder: 4, popular: false, badge: 'Unlimited',
        price: { amount: 35000,  currency: 'INR', billingCycle: 'monthly', label: '₹35,000/mo',   note: 'Unlimited briefs' },
        quantities: { reportsPerMonth: 999, revisionRounds: 3 },
        features: { dedicatedPM: true,  weeklyReport: true,  crmExport: true, companyIntelligence: true, intentData: true },
        support: { type: 'dedicated-pm', label: 'Dedicated Researcher', responseTime: '1 hour' },
        deliverableSummary: 'Unlimited briefs · competitive intel · custom format · dedicated researcher' },
    ],

    'call-intelligence-crm': [
      { tierId: 'credit',  name: 'Credit Only', displayOrder: 1, popular: false, badge: 'Free Setup',
        price: { amount: 0,      currency: 'INR', billingCycle: 'free',    label: 'Free',         note: 'Setup + 10 recordings' },
        quantities: { reportsPerMonth: 0, revisionRounds: 0 },
        features: { dedicatedPM: false, weeklyReport: false },
        support: { type: 'email', label: 'Email Support', responseTime: '48 hours' },
        deliverableSummary: 'Tool setup + 10 call recordings — no CRM sync' },

      { tierId: 'bronze',  name: 'Bronze', displayOrder: 2, popular: false, badge: 'Starter',
        price: { amount: 20000,  currency: 'INR', billingCycle: 'one-time', label: '₹20,000',      note: 'Setup + 1 month' },
        quantities: { reportsPerMonth: 4, revisionRounds: 1 },
        features: { dedicatedPM: false, weeklyReport: true,  crmExport: true  },
        support: { type: 'chat', label: 'Chat Support', responseTime: '24 hours' },
        deliverableSummary: 'Full setup + AI transcription + basic CRM auto-update' },

      { tierId: 'silver',  name: 'Silver',  displayOrder: 3, popular: true,  badge: 'Most Popular',
        price: { amount: 40000,  currency: 'INR', billingCycle: 'one-time', label: '₹40,000',      note: 'Full setup' },
        quantities: { reportsPerMonth: 8, revisionRounds: 2 },
        features: { dedicatedPM: false, weeklyReport: true,  crmExport: true, companyIntelligence: true },
        support: { type: 'priority-chat', label: 'Priority Chat', responseTime: '4 hours' },
        deliverableSummary: 'Full setup + coaching reports + deal risk scoring + CRM sync' },

      { tierId: 'gold',    name: 'Gold',    displayOrder: 4, popular: false, badge: 'Revenue Intel',
        price: { amount: 75000,  currency: 'INR', billingCycle: 'one-time', label: '₹75,000',      note: 'Full setup' },
        quantities: { reportsPerMonth: 12, revisionRounds: 3 },
        features: { dedicatedPM: true,  weeklyReport: true,  crmExport: true, companyIntelligence: true, intentData: true },
        support: { type: 'dedicated-pm', label: 'Dedicated Revenue Analyst', responseTime: '1 hour' },
        deliverableSummary: 'Full stack + AI coaching + competitor flagging + pipeline risk + dedicated analyst' },
    ],

    'virtual-assistant-marketing': [
      { tierId: 'credit',  name: 'Credit Only', displayOrder: 1, popular: false, badge: 'Free Blueprint',
        price: { amount: 0,      currency: 'INR', billingCycle: 'free',    label: 'Free',         note: 'Blueprint only' },
        quantities: { hoursPerWeek: 0, revisionRounds: 0 },
        features: { dedicatedPM: false, weeklyReport: false },
        support: { type: 'email', label: 'Email Support', responseTime: '48 hours' },
        deliverableSummary: 'DoingBlueprint creation — no VA execution included' },

      { tierId: 'bronze',  name: 'Bronze', displayOrder: 2, popular: false, badge: 'Part-Time',
        price: { amount: 25000,  currency: 'INR', billingCycle: 'monthly', label: '₹25,000/mo',   note: '20 hrs/week' },
        quantities: { hoursPerWeek: 20, revisionRounds: 1 },
        features: { dedicatedPM: false, weeklyReport: true,  replacementGuarantee: true },
        support: { type: 'chat', label: 'Chat Support', responseTime: '24 hours' },
        deliverableSummary: 'Part-time VA (20 hrs/week) · DoingBlueprint · weekly report · 14-day replacement' },

      { tierId: 'silver',  name: 'Silver',  displayOrder: 3, popular: true,  badge: 'Most Popular',
        price: { amount: 45000,  currency: 'INR', billingCycle: 'monthly', label: '₹45,000/mo',   note: '40 hrs/week' },
        quantities: { hoursPerWeek: 40, revisionRounds: 2 },
        features: { dedicatedPM: false, weeklyReport: true,  replacementGuarantee: true },
        support: { type: 'priority-chat', label: 'Priority Chat', responseTime: '4 hours' },
        deliverableSummary: 'Full-time dedicated VA · DoingBlueprint · SOP library · weekly report' },

      { tierId: 'gold',    name: 'Gold',    displayOrder: 4, popular: false, badge: 'VA Team',
        price: { amount: 80000,  currency: 'INR', billingCycle: 'monthly', label: '₹80,000/mo',   note: '2 VAs full-time' },
        quantities: { hoursPerWeek: 80, revisionRounds: 3 },
        features: { dedicatedPM: true,  weeklyReport: true,  replacementGuarantee: true },
        support: { type: 'dedicated-pm', label: 'Dedicated VA Manager', responseTime: '2 hours' },
        deliverableSummary: '2 full-time VAs + VA manager · full SOP library · priority replacement' },
    ],

    'ai-expert-matching': [
      { tierId: 'credit',  name: 'Credit Only', displayOrder: 1, popular: false, badge: 'Free Search',
        price: { amount: 0,      currency: 'INR', billingCycle: 'free',    label: 'Free',         note: 'Self-service search' },
        quantities: { candidatesPresented: 1, revisionRounds: 0 },
        features: { dedicatedPM: false, weeklyReport: false, replacementGuarantee: false },
        support: { type: 'email', label: 'Email Support', responseTime: '48 hours' },
        deliverableSummary: 'Browse marketplace yourself — no AI matching or vetting' },

      { tierId: 'bronze',  name: 'Bronze', displayOrder: 2, popular: false, badge: 'Assisted',
        price: { amount: 5000,   currency: 'INR', billingCycle: 'one-time', label: '₹5,000 flat',  note: '1 vetted candidate' },
        quantities: { candidatesPresented: 1, revisionRounds: 1 },
        features: { dedicatedPM: false, weeklyReport: false, replacementGuarantee: false },
        support: { type: 'chat', label: 'Chat Support', responseTime: '24 hours' },
        deliverableSummary: '1 AI-vetted candidate with skill match score + proposal' },

      { tierId: 'silver',  name: 'Silver',  displayOrder: 3, popular: true,  badge: 'Most Popular',
        price: { amount: 0,      currency: 'INR', billingCycle: 'per-unit', label: 'Free + 10% on hire', note: '3 vetted candidates' },
        quantities: { candidatesPresented: 3, revisionRounds: 2 },
        features: { dedicatedPM: false, weeklyReport: false, replacementGuarantee: true  },
        support: { type: 'priority-chat', label: 'Priority Chat', responseTime: '4 hours' },
        deliverableSummary: '3 AI-vetted candidates · negotiated rates · onboarding checklist · 30-day replacement' },

      { tierId: 'gold',    name: 'Gold',    displayOrder: 4, popular: false, badge: 'Concierge',
        price: { amount: 15000,  currency: 'INR', billingCycle: 'one-time', label: '₹15,000 flat', note: 'Includes sourcing manager' },
        quantities: { candidatesPresented: 5, revisionRounds: 3 },
        features: { dedicatedPM: true,  weeklyReport: false, replacementGuarantee: true  },
        support: { type: 'dedicated-pm', label: 'Dedicated Sourcing Manager', responseTime: '2 hours' },
        deliverableSummary: '5 candidates · dedicated sourcing manager · custom vetting criteria · replacement covered' },
    ],
  };

  const tiers = tiersMap[slug] || [];
  return tiers.map(t => ({ ...t, projectId }));
}


// ── 3. MAIN SEED FUNCTION ──────────────────────────────────────────────────────

async function seed() {
  console.log('\n🌱  Starting project seed...\n');

  // Connect
  await mongoose.connect(config.mongoUri);
  console.log('✅  MongoDB connected\n');

  // Clear old data
  const deletedProjects = await ProjectCatalog.deleteMany({});
  const deletedPricing  = await ProjectPricing.deleteMany({});
  console.log(`🗑   Cleared ${deletedProjects.deletedCount} ProjectCatalog docs`);
  console.log(`🗑   Cleared ${deletedPricing.deletedCount}  ProjectPricing docs\n`);

  let totalProjects = 0;
  let totalTiers    = 0;

  for (const data of PROJECTS_DATA) {
    // Insert project
    const project = await ProjectCatalog.create(data);
    totalProjects++;
    console.log(`✅  Project: ${project.title} (${project._id})`);

    // Build and insert 4 pricing tiers referencing this project's _id
    const tiers = buildPricingTiers(project._id, project.slug);
    const inserted = await ProjectPricing.insertMany(tiers);
    totalTiers += inserted.length;
    inserted.forEach(t => console.log(`    💰  ${t.name.padEnd(12)} ₹${String(t.price.amount).padStart(7)} — ${t.deliverableSummary}`));
    console.log('');
  }

  console.log('─────────────────────────────────────────────');
  console.log(`✅  Seeded ${totalProjects} projects`);
  console.log(`✅  Seeded ${totalTiers} pricing tiers`);
  console.log('─────────────────────────────────────────────\n');

  await mongoose.disconnect();
  console.log('🔌  MongoDB disconnected. Done!\n');
}

seed().catch(err => {
  console.error('❌  Seed failed:', err);
  process.exit(1);
});
