const mongoose = require('mongoose');

const exportedLeadSchema = new mongoose.Schema(
  {
    leadId: {
      type: String,
      trim: true
    },
    firstName: {
      type: String,
      trim: true
    },
    lastName: {
      type: String,
      trim: true
    },
    fullName: {
      type: String,
      trim: true
    },
    title: {
      type: String,
      trim: true
    },
    company: {
      type: String,
      trim: true
    },
    email: {
      type: String,
      trim: true
    },
    phone: {
      type: String,
      trim: true
    },
    mobile: {
      type: String,
      trim: true
    },
    industry: {
      type: String,
      trim: true
    },
    sector: {
      type: String,
      trim: true
    },
    segment: {
      type: String,
      trim: true
    },
    country: {
      type: String,
      trim: true
    },
    employees: {
      type: mongoose.Schema.Types.Mixed
    },
    rawData: {
      type: mongoose.Schema.Types.Mixed,
      default: {}
    }
  },
  { _id: false }
);

const userCrmSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'User ID is required'],
      index: true
    },
    crmObjectName: {
      type: String,
      required: [true, 'CRM object name is required'],
      trim: true,
      minlength: [2, 'CRM object name must be at least 2 characters'],
      maxlength: [100, 'CRM object name cannot exceed 100 characters']
    },
    source: {
      type: String,
      enum: ['export', 'manual'],
      default: 'export'
    },
    exportFormat: {
      type: String,
      enum: ['email_only', 'email_phone'],
      required: [true, 'Export format is required']
    },
    totalLeads: {
      type: Number,
      required: [true, 'Total leads count is required'],
      min: [1, 'At least one lead is required']
    },
    searchCriteria: {
      industry: {
        type: String,
        trim: true
      },
      company: {
        type: String,
        trim: true
      },
      companySegment: {
        type: String,
        trim: true
      },
      location: {
        type: String,
        trim: true
      }
    },
    leadIds: [{
      type: String,
      trim: true
    }],
    leads: {
      type: [exportedLeadSchema],
      default: []
    },
    metadata: {
      requestedCount: {
        type: Number,
        min: 0
      },
      matchedCount: {
        type: Number,
        min: 0
      },
      creditsConsumed: {
        type: Number,
        min: 0,
        default: 0
      },
      remainingCreditsAfter: {
        type: Number,
        min: 0
      },
      exportedAt: {
        type: Date,
        default: Date.now
      },
      autoGeneratedName: {
        type: Boolean,
        default: false
      },
      exportedBy: {
        type: String,
        default: 'hotlead-inbox'
      }
    }
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true }
  }
);

userCrmSchema.index({ userId: 1, createdAt: -1 });
userCrmSchema.index({ userId: 1, crmObjectName: 1 });
userCrmSchema.index({ leadIds: 1 });

userCrmSchema.methods.toJSON = function () {
  const crmObject = this.toObject();
  delete crmObject.__v;
  return crmObject;
};

const UserCRM = mongoose.model('UserCRM', userCrmSchema, 'userCRM');

module.exports = UserCRM;
